@startuml
class CoinsController {
}
class BarsService {
}
interface IImageController {
}
class OauthController {
}
interface IClientsController {
}
class CoinsService {
}
class ServerSentEventService {
}
class ClientService {
}
interface BarsFeign {
}
class SpotifyService {
}
interface ITablesController {
}
class BarsController {
}
class TablesService {
}
class SpotifyController {
}
interface IContextService {
}
interface IGamesController {
}
interface IBarsService {
}
class RandomNameService {
}
class SwaggerConstants {
}
interface IClientService {
}
interface CoinsFeign {
}
interface PrizeFeign {
}
class ServerSentEventController {
}
interface IOauthService {
}
class GamesController {
}
class ImageService {
}
class CodesService {
}
interface ISongVotesController {
}
class PrizesController {
}
interface IPrizesService {
}
class GamesService {
}
class ImageController {
}
interface ICoinsController {
}
class ClientsController {
}
interface IServerSentEventService {
}
interface IOauthController {
}
class SongVotesController {
}
interface IRandomNameService {
}
interface IPrizesController {
}
class PartiesService {
}
interface ISpotifyController {
}
interface UsersFeign {
}
interface SpotifyFeign {
}
class CodesController {
}
class PartyController {
}
interface ISpotifyService {
}
class ContextService {
}
class VoteService {
}
class PrizesService {
}
interface ICoinsService {
}
class OwnerService {
}
class OAuthService {
}
interface IRedeemsController {
}
interface IVoteService {
}
interface ICodesService {
}
interface IBarsController {
}
interface ITablesService {
}
interface IOwnerService {
}
interface IGamesService {
}
interface SpotifyTokenFeign {
}
class SpotifyTokenFeign$Configuration {
}
class RedeemsController {
}
class PartyTablesController {
}
class TablesController {
}
interface ICodesController {
}
interface IPartyController {
}
interface IPartiesService {
}
interface IPartyTablesController {
}
interface IServerSentEventController {
}
interface IImageService {
}


ICoinsController <|.. CoinsController
IBarsService <|.. BarsService
ContextService <|-- BarsService
IOauthController <|.. OauthController
ICoinsService <|.. CoinsService
ContextService <|-- CoinsService
IServerSentEventService <|.. ServerSentEventService
IClientService <|.. ClientService
ISpotifyService <|.. SpotifyService
ContextService <|-- SpotifyService
IBarsController <|.. BarsController
ITablesService <|.. TablesService
ContextService <|-- TablesService
ISpotifyController <|.. SpotifyController
IRandomNameService <|.. RandomNameService
IServerSentEventController <|.. ServerSentEventController
IGamesController <|.. GamesController
IImageService <|.. ImageService
ContextService <|-- ImageService
ICodesService <|.. CodesService
ContextService <|-- CodesService
IPrizesController <|.. PrizesController
IGamesService <|.. GamesService
ContextService <|-- GamesService
IImageController <|.. ImageController
IClientsController <|.. ClientsController
ISongVotesController <|.. SongVotesController
IPartiesService <|.. PartiesService
ContextService <|-- PartiesService
ICodesController <|.. CodesController
IPartyController <|.. PartyController
IContextService <|.. ContextService
IVoteService <|.. VoteService
IPrizesService <|.. PrizesService
ContextService <|-- PrizesService
IOwnerService <|.. OwnerService
IOauthService <|.. OAuthService
UserDetailsService <|.. OAuthService
SpotifyTokenFeign +.. SpotifyTokenFeign$Configuration
IRedeemsController <|.. RedeemsController
IPartyTablesController <|.. PartyTablesController
ITablesController <|.. TablesController
@enduml