server:
  servlet:
    context-path: /bff
  port: '8080'
spring:
  application:
    name: bff

#LOGIN GOOGLE
google:
  client:
    id: 361460326222-60aal4bkqjt0t0mpl42s4ruo3qm9lpqn.apps.googleusercontent.com

bff:
  path:
    actuator: /actuator
feign:
  coins-ms:
    url: http://localhost:8081
    req-map: coins
    name: coins
  bars-ms:
    url: http://localhost:8082
    name: bars
    req-map: bars
  users-ms:
    req-map: users
    url: http://localhost:8084
    name: users
  prizes-ms:
    url: http://localhost:8083
    name: prizes
    req-map: prizes




